#!/bin/bash

# Update the package manager repository
sudo apt update

# Install the necessary dependencies
sudo apt install -y curl

# Download and install the crowdsec script
curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | sudo bash
sudo apt-get install crowdsec

# Configure and start the crowdsec service
sudo systemctl enable --now crowdsec

# Check the status of the crowdsec service
sudo systemctl status crowdsec

# Check the logs for any issues during the installation process
sudo journalctl -u crowdsec


# Output to Wazuh
echo 'outputs:
  - type: wazuh
    server: "WAZUH_SERVER_IP"
    port: 55000
    protocol: udp' >> /etc/crowdsec/daemon.yaml

# Restart Crowdsec
sudo systemctl restart crowdsec

# Install bouncer - This will do the blocking
sudo apt install crowdsec-firewall-bouncer-iptables